### ISSUE TITLE
Suggestion: In azan notification, include "Next: [Prayer] [Time]"

### ISSUE THREAD

**Issue by yusufmte** [meypod/al-azan#19] opened 2022-12-20 18:00 UTC
Assalamu alaikum,

Thanks friend for making this wonderful app, it has been my go-to Azan app, has been working very smoothly, and has all the features needed.

Adding the Azan time to the notification text was a very helpful recent addition. My suggestion is to include the "Next: [Prayer] [Time]" (for example, "Next: Asr, 1407") in the notification text as well. That would be helpful for my purposes, as I use the app to send azan notifications to my watch. This is a subjective design decision of course, but just wanted to mention it as a possibility or maybe even an option.

Thank you!

**Comment by meypod** [comment] 2022-12-20 19:51
Va alaykum assalam,

I'll try to add it as an option, because that will probably add a little processing cost

And about your problem, did you restarting the app ? 
Also can you check in which version you was and after which it doesn't work properly anymore? Because I always use the latest version myself to make sure nothing is broken

Thank you

**Comment by meypod** [comment] 2022-12-21 06:42
I'm glad it's working fine
Adding this feature may take a while though since I can't work on it anytime soon (at least a week later)

**Comment by yusufmte** [comment] 2022-12-21 14:48
> I'm glad it's working fine
> Adding this feature may take a while though since I can't work on it anytime soon (at least a week later)

Of course, take your time! Thanks for considering it.

**Comment by meypod** [comment] 2022-12-22 03:40
I guess I can either add it in the same line Or on the next line of notification body
Which approach do you think would be displayed better on your watch ?
Does your watch handle multiline notifications well or does it need to be on the same line as the current adhan time

**Comment by yusufmte** [comment] 2022-12-22 04:42
> I guess I can either add it in the same line Or on the next line of notification body
> Which approach do you think would be displayed better on your watch ?
> Does your watch handle multiline notifications well or does it need to be on the same line as the current adhan time

It handles multiline notifications well, and I think adding it on the next line would work best. Thank you for working on it!

**Comment by meypod** [comment] 2022-12-24 10:37
I have added this feature, but slightly different than multiline since making the body multiline would have make it slightly more complex
instead I saw notifee/android notification has a `subtitle` property as well, I used that for time instead and put the extra info in the body, also added an option for it inside notification & sound settings

I will close this issue once It's released

**Comment by meypod** [comment] 2022-12-30 21:26
Released in [v1.9.0](https://github.com/meypod/al-azan/releases/tag/v1.9.0) 
Let me know if it's not behaving as you expect

**Comment by yusufmte** [comment] 2023-01-08 00:23
Assalamu alaikum

Thank you very much for adding this feature! 👍

It looks great 😌 The only unexpected behavior is that turning on this option seems to overwrite the current prayer time, so it will either show only the current prayer time or only the next. See below:

![Screenshot_20230107-191716-577.png](https://user-images.githubusercontent.com/45940010/211175102-a6e28596-1b30-472b-856c-ff9b364c78c4.png)

![Screenshot_20230107-152238~2.png](https://user-images.githubusercontent.com/45940010/211175106-d90f42b7-c6a1-4482-a267-03559940cd12.png)

If intentional due to limitations of the code, this is fine, just wanted to point it out in case it is not intentional.

**Comment by meypod** [comment] 2023-01-08 08:29
Well this is completely intentional, because on xiaomi phones at least, you can't see the subtitle with MIUI style notification. but you have missed one thing, the information is still there when you enable the option, it's just shown as subtitle
here is what I mean:
![211175102-a6e28596-1b30-472b-856c-ff9b364c78c4](https://user-images.githubusercontent.com/106489260/211187159-426c96bf-2cc4-4a62-9d04-058a695ec21f.png)

**Comment by yusufmte** [comment] 2023-01-08 12:38
Ah I see! I did notice it is there on the phone, but it does not seem to get sent to my watch, only the title and body are sent to the watch (can show a screenshot later). I don't know necessarily that this would extend to other kinds of watches though / It doesn't need any changing if it would require added complexity 🙂 I still like leaving the option on as the next prayer time is more important.

**Comment by meypod** [comment] 2023-01-08 13:56
hmm, it certainly does add some complexity
but I re-open and might take another look some time later, no promises though

**Comment by meypod** [comment] 2023-01-13 15:29
I'm sorry that I didn't look into it properly, it was actually very very simple ...
it would be nice if you could try out the new pre release version to see if this is now working as intended or not (so we can close this issue)
just watch out for notification and phone permissions if you are on android 13, I have not implemented the dialogs yet, so you have to go to app settings to enable them manually

**Comment by yusufmte** [comment] 2023-01-15 00:24
Tested this pre-release version:

It's odd, it works as expected on the phone, but only the second line goes to the watch 🤔 See screenshots:

![Screenshot_20230114-071426-335](https://user-images.githubusercontent.com/45940010/212502866-38cfb535-e633-49e0-948a-778d235b0dc1.png)
![IMG_20230114_071349939~2](https://user-images.githubusercontent.com/45940010/212502871-85333cf0-f5d9-4d13-bc9c-33f913e3eddc.jpg)

It might just be my watch. But I've tested other multiline notifications which do work on my watch.

Understandable if you want to close the issue as it might just be from my end. Alternatively, a simple solution might just be to use one line, as in:

07:12 - Next: Dhuhr, 11:51

Thank you for working on it 🙂

**Comment by meypod** [comment] 2023-01-15 08:35
thank you for testing it
I see
well I don't have other means of multi lining sadly
I guess I go with the simple solution for this, because there's not much we can do it seems
and if you are facing this issue, chances are many other will as well
so I'll go with the suggestion

**Comment by meypod** [comment] 2023-01-15 19:11
I would be happy if you test [v1.10.0-rc.13](https://github.com/meypod/al-azan/releases/tag/v1.10.0-rc.13),
I want to see if this change is good (your suggestion), and this is probably the last pre release that I'm testing before releasing v1.10.0, so there's tons of improvements, so I would like to get feedback on how well this version works as well

**Comment by yusufmte** [comment] 2023-01-15 22:41
Working great! Thank you again for all your work on it 🙂

![IMG_20230115_163157926~2.jpg](https://user-images.githubusercontent.com/45940010/212571051-870a7ddd-865f-4bea-a7b8-17b65a1a1523.jpg)

**Comment by meypod** [comment] 2023-01-16 02:46
thank you for testing
feel free to open an issue if anything comes up ;)

**Closed by meypod** 2023-01-16 02:46 UTC
Labels: enhancement
