### ISSUE TITLE
Highlight the current Payer Time and not the
next/upcoming

### ISSUE THREAD

**Issue by sami155** [meypod/al-azan#56] opened 2023-05-09 12:17 UTC
_Sorry I just couldn't submit this under "Feature Requests". Github always gave me a error message_

**Is your feature request related to a problem?
Please describe.**
When using the widget, I always get confused
on what Prayer Time it currently is. When
looking at the widget the Attention of the User
gets directly to the colored/inked/highlighted
Time & Name of the _next_ Prayer Time.

**Describe the solution you'd like**
I think coloring/marking the current Prayer
Time is a solution to this.

**Additional context**
_Instead of Asr being highlighted, Dhuhr
should be. And when the prayer time Maghrib
begins, Maghrib should be highlighted_
![Screenshot_20230509261_Al-Azan.png](https://github.com/meypod/al-azan/assets/56385412/4a62b81f-9d7c-49f3-8db5-4251c038c6ca)

**Comment by meypod** [comment] 2023-05-09 13:51
Sure, I'll look into it when I have time

**Comment by meypod** [comment] 2023-05-09 14:09
hmm,
but this is the same behavior as the UI in app
changing it means also changing the UI's behavior in app as well

**Comment by meypod** [comment] 2023-05-09 14:36
so, is this what you expect the main screen behavior to be as well ?

**Comment by meypod** [comment] 2023-05-11 02:05
I have released a test version, I need you to test it for a few days at least to see if it got any bugs

you can find it here: https://github.com/meypod/al-azan/releases/tag/v1.14.5-rc

thank you

**Comment by meypod** [comment] 2023-05-15 01:22
hi
thanks for the accurate reproduction video and nice finding !
I'll look into it as soon as I have time

**Comment by joewood9364** [comment] 2023-05-15 12:34
Agree with author it's good to highlight the current prayer in both app and widget please!

**Comment by meypod** [comment] 2023-05-16 01:44
one thing to note though, due to the way it works, it won't stop highlighting when a prayer time has passed

say for example, Dhuhr is highlighted, then you have hidden Maghrib and Isha
when time goes past maghrib or Isha, you will still see Dhuhr getting highlighted

I thought I should note this, because someone may get confused by it later thinking it will exactly take into account the time range of Prayers, which is not the case

I released a fix for it here: https://github.com/meypod/al-azan/releases/tag/v1.14.5-rc3
will be available in ~ 20 min in GitHub releases

please let me know if anything else came up

**Comment by meypod** [comment] 2023-05-17 06:32
You are right, it was my mistake to not test it properly, I'm sorry

It was not as simple as I initially thought
made a fix and checked it multiple times
it should be fixed now
also apparently there was a small bug with the next prayer highlight inside the home screen, fixed that as well

you can get this here: https://github.com/meypod/al-azan/releases/tag/v1.14.5-rc4
will be available on GitHub in ~ 20 min

**Comment by meypod** [comment] 2023-05-26 00:04
since a week has passed and this seems to be working as expected, I'm releasing this and closing this issue

feel free to reply here or open a new issue if anything comes up

**Closed by meypod** 2023-05-26 00:04 UTC
Labels: enhancement
